name: Register All Container Images
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  register-x64:
    uses: ./.github/workflows/register-x64.yml
    secrets: inherit
    
  register-arm64:
    uses: ./.github/workflows/register-arm64.yml
    secrets: inherit
    
  create-manifest:
    needs: [register-x64, register-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Get release tag
        id: get_tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 1200
        
      - name: Pull architecture-specific images
        run: |
          # Create platform-specific tags for identification
          AMD64_TAG="registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}-amd64"
          ARM64_TAG="registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}-arm64"
          
          # Pull the AMD64 image
          docker pull registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}
          docker tag registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} $AMD64_TAG
          
          # Pull the ARM64 image (this will be from the arm64 workflow)
          docker pull registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}
          docker tag registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} $ARM64_TAG
          
      - name: Create and push multi-arch manifest
        run: |
          # Use the platform-specific tags created earlier
          AMD64_TAG="registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}-amd64"
          ARM64_TAG="registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}-arm64"
          
          # Create the manifest list
          docker manifest create joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} \
            --amend $AMD64_TAG \
            --amend $ARM64_TAG
            
          # Annotate the manifest with architecture information
          docker manifest annotate joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} \
            $AMD64_TAG --arch amd64 --os linux
            
          docker manifest annotate joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} \
            $ARM64_TAG --arch arm64 --os linux
            
          # Push the manifest list
          docker manifest push joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}