name: Register tentacle-ui to the private container registry
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN  }}
      - name: Get release tag
        id: get_tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Build container image
        run: docker build -t registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag for Docker Hub
        run: docker tag registry.digitalocean.com/jar-containers/joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }} joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}
      - name: Push to Docker Hub
        run: docker push joyautomation/tentacle-ui:${{ steps.get_tag.outputs.VERSION_TAG }}
